import type { createClient as createBrowserClientFn } from "./clients/browser";

export { createClient as createBrowserClient } from "./clients/browser";
export { createServerClient, type CookieAdapter } from "./clients/server";
export { createServiceClient } from "./clients/service";
export { createAuthVerificationClient } from "./clients/auth-verify";

export type {
  Database,
  Json,
  Tables,
  TablesInsert,
  TablesUpdate,
  Profile,
  Tenant,
  Membership,
  Product,
  Subscription,
  Entitlement,
  AdminAuditLog,
  PlatformAviso,
  PlatformAvisoDescartado,
  MembershipRole,
  ProductStatus,
  SubscriptionStatus,
  EntitlementStatus,
  CountryCode,
  PlatformAvisoTipo,
  // Enums del vertical Minimarket
  MmModulo,
  MmMovTipo,
  MmCompraEstado,
  MmDocTipo,
  MmVentaEstado,
  MmMetodoPago,
  MmCajaEstado,
  MmCajaMovTipo,
  MmTasaFuente,
  MmTipoTasa,
  MmFiadoEstado,
  MmTipoVenta,
  MmDeudaEstado,
  MmGastoCategoria,
  // Filas del vertical Minimarket
  MmSucursal,
  MmUsuarioSucursal,
  MmRol,
  MmPermisoRol,
  MmConfigNegocio,
  MmCategoria,
  MmProducto,
  MmProductoCodigo,
  MmPrecio,
  MmInventario,
  MmMovimientoInventario,
  MmProveedor,
  MmCompra,
  MmCompraItem,
  MmCliente,
  MmFiado,
  MmAbonoFiado,
  MmVenta,
  MmVentaItem,
  MmPagoVenta,
  MmCajaSesion,
  MmCajaMovimiento,
  MmTasaCambio,
  MmStock,
  MmSaldoCliente,
  MmResumenProveedor,
  MmCategoriaDeuda,
  MmDeuda,
  MmAbonoDeuda,
  MmSaldoDeuda,
  MmGastoOperativo,
  MmOtroIngreso,
  MmCuentaBancaria,
  MmCuentaMovimiento,
  MmSaldoInicial,
  MmSaldoCuentaBancaria,
  MmCreditoCliente,
  MmCreditoClienteTipo,
  MmSaldoCreditoCliente,
  MmPresupuestoEstado,
  MmPresupuesto,
  MmPresupuestoItem,
  // Enums del vertical Servicio Técnico
  StOrdenEstado,
  StTipoEquipo,
  StLineaTipo,
  StMetodoPago,
  StTasaFuente,
  // Filas del vertical Servicio Técnico
  StConfig,
  StTasaCambio,
  StCliente,
  StRepuesto,
  StEquipo,
  StOrden,
  StLineaOrden,
  StPagoOrden,
  StResumenCliente,
  // Enums del vertical Condominio
  CndTipoCondominio,
  CndMetodoReparto,
  CndTipoUnidad,
  CndGastoCategoria,
  CndMetodoPago,
  CndTasaFuente,
  CndTipoDocumento,
  CndTipoIdentificacion,
  CndEstadoReportePago,
  CndEstadoGastoEspecial,
  CndModoGastoEspecial,
  CndFondoTipo,
  CndFondoOrigen,
  CndRepartoEstado,
  CndRepartoAjusteTipo,
  CndRepartoAjusteEfecto,
  // Filas del vertical Condominio
  CndCondominio,
  CndUnidad,
  CndGastoComun,
  CndCuota,
  CndPagoCuota,
  CndConfig,
  CndTasaCambio,
  CndAreaComun,
  CndReserva,
  CndDocumento,
  CndInquilino,
  CndReportePago,
  CndReportePagoParte,
  CndGastoEspecial,
  CndGastoEspecialParte,
  CndFondoMovimiento,
  CndReparto,
  CndRepartoAjuste,
  CndInventarioCategoria,
  CndInventarioItem,
} from "./types/database";

export type SupabaseClient = ReturnType<typeof createBrowserClientFn>;
